server:
  port: ${services.ports.organization}
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9999
  data:
    mongodb:
      uri: mongodb://localhost/demo_auth
      auto-index-creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/{your-db}
    username:
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true
        jdbc:
          lob:
            non_contextual_creation: true
        #default_schema: users
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create-drop
  sql:
    init:
      mode: never